name: Pull request validation

on:
  pull_request:
    branches: [main]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: clear cache
      run: yarn cache clean

    - name: install
      run: yarn

    - name: lint
      run: yarn lint

    - name: check build
      run: yarn build

    - name: unit tests for the core lib
      run: yarn core test

    - name: unit tests for the command line interface (cli)
      run: yarn components test

    - name: unit tests for the plugins
      run: yarn express test
